<?php
/**
 * Feed HTTP response value object.
 *
 * @package SitePhonebooks
 */

namespace SitePhonebooks\Feed;

defined( 'ABSPATH' ) || exit;

/**
 * Plain value object so delivery logic can be tested without sending headers.
 */
final class Feed_Response {

	/**
	 * HTTP status.
	 *
	 * @var int
	 */
	public $status = 200;

	/**
	 * Headers (name => value).
	 *
	 * @var array<string,string>
	 */
	public $headers = array();

	/**
	 * Body (empty for HEAD / 304).
	 *
	 * @var string
	 */
	public $body = '';

	/**
	 * Phonebook the response relates to (for request logging), if any.
	 *
	 * @var int
	 */
	public $phonebook_id = 0;

	/**
	 * Constructor.
	 *
	 * @param int    $status  Status.
	 * @param array  $headers Headers.
	 * @param string $body    Body.
	 */
	public function __construct( $status = 200, array $headers = array(), $body = '' ) {
		$this->status  = (int) $status;
		$this->headers = $headers;
		$this->body    = (string) $body;
	}

	/**
	 * Build a minimal XML error response without any detail that could leak
	 * configuration or data.
	 *
	 * @param int    $status  HTTP status.
	 * @param string $message Short generic message.
	 * @return Feed_Response
	 */
	public static function error( $status, $message ) {
		$body = '<?xml version="1.0" encoding="utf-8"?>' . "\n" . '<Error status="' . (int) $status . '">' . htmlspecialchars( $message, ENT_XML1 | ENT_QUOTES, 'UTF-8' ) . '</Error>' . "\n";
		return new self(
			$status,
			array(
				'Content-Type'           => 'application/xml; charset=utf-8',
				'Cache-Control'          => 'no-store, max-age=0',
				'X-Robots-Tag'           => 'noindex, nofollow',
				'X-Content-Type-Options' => 'nosniff',
				'Content-Length'         => (string) strlen( $body ),
			),
			$body
		);
	}

	/**
	 * Send headers and body, then stop WordPress. Any stray output buffered
	 * by other code is discarded so the response is XML only.
	 */
	public function send() {
		while ( ob_get_level() > 0 ) {
			ob_end_clean();
		}
		status_header( $this->status );
		foreach ( $this->headers as $name => $value ) {
			header( $name . ': ' . $value, true );
		}
		header_remove( 'X-Pingback' );
		if ( '' !== $this->body ) {
			echo $this->body; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- XML generated by XMLWriter.
		}
		exit;
	}
}
